###
# These are your site settings
# expects jekyll > 3.7
###

# Site settings
title: Jake Volin
email: ""
description: > # this means to ignore newlines until ''baseurl:''
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://jakevolin.com
# atom.xml feed configuration
author:
  name: Jake Volin
  email: ""
  url: https://jakevolin.com
# the subpath of your site, e.g. /blog/
baseurl: ""
twitter_username: jakevolin
github_username: jakevolin

# Build settings
markdown: kramdown
source: .
destination: ./docs

# Pagination settings
paginate: 3
paginate_path: "blog/page:num"

# Collections are groups of categories you might have pages for (eg: staff_members)
collections:
  - podcasts

# Google Analytics
ga_id: "UA-138037311-1"
ga_domain: "auto"

#
contact:
  phone: 720-555-5555
  email: fake@email.com
  location: Denver Colorado

# Keywords are strings that influence the search algorithms
keywords:
  - Jake
  - Volin
  - Financial
  - Podcast
